INSERT INTO "public"."event_reports" ("id", "title", "date", "venue", "organized_by", "academic_year", "society_code", "category", "photo_url", "photo_urls", "certificate_urls", "event_overview", "key_highlights", "conclusion_text", "status", "created_at") VALUES (1, 'IEEE Madras Section Coimbatore Hub Congress 2025', '13 September 2025', 'PSG Institute of Technology and Applied Research, Coimbatore', 'IEEE Madras Section', '2025-2026', 'IEEE SB', 'Hub Congress', 'https://wlbgdlolgjccvbuvutiw.supabase.co/storage/v1/object/public/reports/report_1787159781270_0_hbpahood5hs.png', '["https://wlbgdlolgjccvbuvutiw.supabase.co/storage/v1/object/public/reports/report_1787159781270_0_hbpahood5hs.png","https://wlbgdlolgjccvbuvutiw.supabase.co/storage/v1/object/public/reports/report_1787159782174_1_p2otpn9q7w.png","https://wlbgdlolgjccvbuvutiw.supabase.co/storage/v1/object/public/reports/report_1787159782687_2_2ed33p79051.png"]', null, 'I had the privilege of participating in the IEEE Madras Section Coimbatore Hub Congress 2025 held at PSG Institute of Technology and Applied Research, Coimbatore. The event brought together distinguished IEEE leaders, student representatives, and members from various IEEE Student Branches, providing an excellent platform for knowledge sharing, leadership development, and collaboration.', 'During the Congress, I had the opportunity to interact with IEEE Madras Section Office Bearers and fellow student representatives, gaining valuable insights into: 
• IEEE leadership and effective student branch management. 
• Planning and execution of technical and professional activities. 
• Opportunities available through IEEE for students and young professionals. 
• Building strong professional networks and collaborations.
• Encouraging innovation, technical knowledge, and active student participation. The interactions and discussions provided a broader understanding of the role of IEEE in developing technical skills, leadership qualities, and professional connections among engineering students.', null, 'PUBLISHED', '2026-08-19 17:17:02.123281+00'), (2, 'GIEEE Section Expert Talk on Financial Administration & Funding Process', '16 August 2026', 'Park Elanza, Chennai', 'IEEE Madras Section & GIEEE', '2025-2026', 'IEEE SB', 'Hub Congress', 'https://wlbgdlolgjccvbuvutiw.supabase.co/storage/v1/object/public/reports/report_1787159894432_0_gma1gto3k8b.jpeg', '["https://wlbgdlolgjccvbuvutiw.supabase.co/storage/v1/object/public/reports/report_1787159894432_0_gma1gto3k8b.jpeg","https://wlbgdlolgjccvbuvutiw.supabase.co/storage/v1/object/public/reports/report_1787159896157_1_12z1oxiz0nj.jpeg","https://wlbgdlolgjccvbuvutiw.supabase.co/storage/v1/object/public/reports/report_1787159897095_2_v0uj3rpcoxp.jpeg","https://wlbgdlolgjccvbuvutiw.supabase.co/storage/v1/object/public/reports/report_1787159899025_3_psf2xy5hml.jpeg","https://wlbgdlolgjccvbuvutiw.supabase.co/storage/v1/object/public/reports/report_1787159900186_4_qh1qpif2dt7.jpeg"]', null, 'I had the opportunity to participate in the GIEEE Section Expert Talk on Financial Administration & Funding Process, organized by IEEE Madras Section and GIEEE. The session provided valuable insights into the financial administration and funding procedures followed within IEEE activities. The expert session focused on important aspects such as financial planning, funding procedures, transparent financial management, documentation, accountability, and effective utilization of funds. The session helped us understand how proper financial administration plays an important role in successfully organizing IEEE events and activities.', 'The session provided practical knowledge about:
Understanding IEEE financial administration and funding procedures. 
Maintaining transparency and accountability in financial activities. 
Proper planning and utilization of funds for IEEE events. 
Following appropriate documentation and financial procedures. 
Managing funds responsibly while conducting student branch activities.', null, 'PUBLISHED', '2026-08-19 17:19:59.896405+00');